/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class example_Iloczyn */

#ifndef _Included_example_Iloczyn
#define _Included_example_Iloczyn
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     example_Iloczyn
	 * Method:    transcode
	 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
	 */
	JNIEXPORT void JNICALL Java_example_Iloczyn_transcode
	(JNIEnv*, jobject, jstring, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
