/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TranscodeApp_Transcoder */

#ifndef _Included_TranscodeApp_Transcoder
#define _Included_TranscodeApp_Transcoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TranscodeApp_Transcoder
 * Method:    transcode
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_TranscodeApp_Transcoder_transcode
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
